#ifndef COLORTEMPLATE_GLOBAL_H
#define COLORTEMPLATE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COLORTEMPLATE_LIBRARY)
#  define COLORTEMPLATE_EXPORT Q_DECL_EXPORT
#else
#  define COLORTEMPLATE_EXPORT Q_DECL_IMPORT
#endif

#endif // COLORTEMPLATE_GLOBAL_H
